name: 'review-app'

services: 
  review-api:
    image: registry:5000/review-api
    container_name: review-api
    restart: always
    env_file: api.env
    depends_on:
      - mariadb
    networks:
      - review-app-network
      - review-back-network

  mariadb:
    container_name: mariadb
    image: mariadb:10.3
    restart: always
    command: --lower_case_table_names=1
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
    networks:
      - review-back-network

networks:
  review-app-network:
    external: true
  review-back-network:
